// Synthetic demonstration recipes; no household records are bundled.
export const ingredient = (
  k,
  n,
  q,
  u,
  group = "Produce",
  note = "",
  original = null,
) => ({ k, n, q, u, group, note, original });
export const recipes = [
  {
    id: "orzo",
    title: "Lemon & chickpea orzo",
    description: "One pot, a little lemon, and very little washing up.",
    course: "main",
    cuisine: "Mediterranean",
    diets: ["vegan"],
    tags: ["Weeknight", "One pot"],
    time: 25,
    servings: 4,
    source: "Example recipe",
    favorite: true,
    ingredients: [
      ingredient("orzo", "Orzo", 250, "g", "Pantry"),
      ingredient(
        "chickpea-can",
        "Chickpeas",
        1,
        "can",
        "Pantry",
        "400 g can, drained",
      ),
      ingredient("lemon", "Lemon", 1, "", "Produce", "zest and juice"),
      ingredient("olive-oil", "Olive oil", 30, "ml", "Pantry", "", {
        q: 2,
        u: "tbsp",
      }),
      ingredient("stock", "Vegetable stock", 600, "ml", "Pantry"),
      ingredient("spinach", "Baby spinach", 80, "g"),
      ingredient("salt", "Salt", null, "", "Pantry", "to taste"),
    ],
    steps: [
      {
        title: "Get everything ready",
        text: "Zest and juice the lemon, drain the chickpeas, and rinse the spinach. Keep the stock close by.",
        ids: ["lemon", "chickpea-can", "spinach", "stock"],
      },
      {
        title: "Toast the orzo",
        text: "Warm the olive oil in a wide pan over medium heat. Add the orzo and stir until lightly golden.",
        ids: ["olive-oil", "orzo"],
        mins: 2,
      },
      {
        title: "Let it simmer",
        text: "Add the stock and chickpeas. Simmer gently, stirring occasionally, until the orzo is tender. Add a splash of water if needed.",
        ids: ["stock", "chickpea-can"],
        mins: 10,
      },
      {
        title: "Finish with lemon",
        text: "Fold in the spinach, lemon zest, and juice. Stir until the leaves wilt. Taste, season, and serve.",
        ids: ["spinach", "lemon", "salt"],
      },
    ],
    note: "Add the lemon at the end for a brighter flavor.",
  },
  {
    id: "tomato",
    title: "Roasted tomato pasta",
    description: "Sweet tomatoes, garlic, and your favorite pasta.",
    course: "main",
    cuisine: "Italian",
    diets: ["vegan"],
    tags: ["Comfort food"],
    time: 35,
    servings: 2,
    source: "Example recipe",
    favorite: true,
    ingredients: [
      ingredient("tomato", "Cherry tomatoes", 300, "g"),
      ingredient("pasta", "Pasta", 200, "g", "Pantry"),
      ingredient("olive-oil", "Olive oil", 30, "ml", "Pantry", "", {
        q: 2,
        u: "tbsp",
      }),
      ingredient("garlic", "Garlic", 2, "cloves"),
      ingredient("basil", "Basil", null, "", "Produce", "a small handful"),
    ],
    steps: [
      {
        title: "Roast the tomatoes",
        text: "Heat the oven to 200°C. Toss tomatoes and garlic with olive oil in a baking dish. Roast until the tomatoes soften and blister.",
        ids: ["tomato", "garlic", "olive-oil"],
        mins: 20,
      },
      {
        title: "Cook the pasta",
        text: "Cook the pasta according to its package directions. Keep a cup of cooking water before draining.",
        ids: ["pasta"],
      },
      {
        title: "Bring it together",
        text: "Mash the roasted tomatoes lightly. Toss with the pasta and a splash of cooking water. Finish with basil.",
        ids: ["basil", "pasta"],
      },
    ],
    note: "Keep some pasta water; it makes the sauce silky.",
  },
  {
    id: "potato",
    title: "Crispy potatoes & tahini",
    description: "Golden edges and a generous drizzle of sauce.",
    course: "side",
    cuisine: "Middle Eastern",
    diets: ["vegan", "gluten_free"],
    tags: ["Crowd pleaser"],
    time: 45,
    servings: 4,
    source: "Example recipe",
    favorite: false,
    ingredients: [
      ingredient("potato", "Potatoes", 600, "g"),
      ingredient("olive-oil", "Olive oil", 30, "ml", "Pantry"),
      ingredient("tahini", "Tahini", 60, "g", "Pantry"),
      ingredient("lemon-juice", "Lemon juice", 30, "ml"),
      ingredient("water", "Water", 45, "ml", "Pantry"),
    ],
    steps: [
      {
        title: "Prepare the potatoes",
        text: "Heat the oven to 220°C. Cut the potatoes into even chunks and toss with olive oil.",
        ids: ["potato", "olive-oil"],
      },
      {
        title: "Roast until golden",
        text: "Spread the potatoes on a tray with room between them. Roast, turning halfway through, until golden and tender.",
        ids: ["potato"],
        mins: 35,
      },
      {
        title: "Make the sauce",
        text: "Whisk tahini with lemon juice. Add water a little at a time until smooth. Spoon over the potatoes.",
        ids: ["tahini", "lemon-juice", "water"],
      },
    ],
    note: "",
  },
  {
    id: "pancakes",
    title: "Slow-morning pancakes",
    description: "The little stack everyone comes back for.",
    course: "breakfast",
    cuisine: "",
    diets: ["vegetarian"],
    tags: ["Weekend"],
    time: 20,
    servings: 4,
    source: "Example recipe",
    favorite: false,
    ingredients: [
      ingredient("flour", "Plain flour", 180, "g", "Pantry"),
      ingredient("milk", "Milk", 240, "ml", "Dairy & eggs"),
      ingredient("egg", "Eggs", 2, "", "Dairy & eggs"),
      ingredient("baking-powder", "Baking powder", 8, "g", "Pantry"),
      ingredient("honey", "Honey", 30, "ml", "Pantry"),
    ],
    steps: [
      {
        title: "Mix the dry ingredients",
        text: "Combine flour and baking powder in a bowl.",
        ids: ["flour", "baking-powder"],
      },
      {
        title: "Make the batter",
        text: "Whisk milk, eggs, and honey together. Fold into the dry ingredients just until combined.",
        ids: ["milk", "egg", "honey"],
      },
      {
        title: "Cook in batches",
        text: "Heat a lightly greased pan over medium heat. Spoon in batter. Turn when bubbles form and cook until the centers are set.",
        ids: [],
      },
    ],
    note: "A few lumps in the batter are fine.",
  },
  {
    id: "salad",
    title: "The everyday chopped salad",
    description: "Crunchy, herby, and ready for the middle of the table.",
    course: "salad",
    cuisine: "Israeli",
    diets: ["vegan", "gluten_free"],
    tags: ["Fresh & simple", "No cook"],
    time: 10,
    servings: 4,
    source: "Example recipe",
    favorite: true,
    ingredients: [
      ingredient("cucumber", "Cucumbers", 2, ""),
      ingredient("tomato", "Cherry tomatoes", 300, "g"),
      ingredient("lemon-juice", "Lemon juice", 30, "ml"),
      ingredient("olive-oil", "Olive oil", 15, "ml", "Pantry"),
      ingredient("parsley", "Parsley", null, "", "Produce", "a handful"),
    ],
    steps: [
      {
        title: "Chop it small",
        text: "Dice the cucumbers and tomatoes. Finely chop the parsley.",
        ids: ["cucumber", "tomato", "parsley"],
      },
      {
        title: "Dress and serve",
        text: "Toss with lemon juice and olive oil. Season to your liking and serve immediately.",
        ids: ["lemon-juice", "olive-oil"],
      },
    ],
    note: "",
  },
  {
    id: "soup",
    title: "Red lentil soup",
    description: "A soft, warming bowl for a quieter evening.",
    course: "soup",
    cuisine: "",
    diets: ["vegan"],
    tags: ["Make ahead", "Freezer friendly"],
    time: 30,
    servings: 4,
    source: "Example recipe",
    favorite: false,
    ingredients: [
      ingredient("lentil", "Red lentils", 200, "g", "Pantry"),
      ingredient("carrot", "Carrots", 2, ""),
      ingredient("onion", "Onion", 1, ""),
      ingredient("olive-oil", "Olive oil", 15, "ml", "Pantry"),
      ingredient("stock", "Vegetable stock", 1000, "ml", "Pantry"),
    ],
    steps: [
      {
        title: "Start with the vegetables",
        text: "Chop the onion and carrots. Warm olive oil in a pot and soften the vegetables.",
        ids: ["onion", "carrot", "olive-oil"],
      },
      {
        title: "Add the lentils",
        text: "Rinse the lentils, then add them with the stock. Bring to a gentle simmer.",
        ids: ["lentil", "stock"],
      },
      {
        title: "Simmer and finish",
        text: "Cook until the lentils are soft. Blend partially if you prefer a smoother texture, and season to taste.",
        ids: [],
        mins: 20,
      },
    ],
    note: "Add a squeeze of lemon just before serving.",
  },
];
const sampleEquipment = {
  orzo: [
    "Wide pan",
    "Hob",
    "Measuring jug",
    "Fine grater",
    "Colander",
    "Wooden spoon",
    "Chopping board",
    "Knife",
  ],
  tomato: [
    "Oven",
    "Baking dish",
    "Large pot",
    "Hob",
    "Colander",
    "Chopping board",
    "Knife",
  ],
  potato: [
    "Oven",
    "Baking tray",
    "Mixing bowl",
    "Whisk",
    "Chopping board",
    "Knife",
  ],
  pancakes: [
    "Mixing bowl",
    "Measuring jug",
    "Whisk",
    "Frying pan",
    "Hob",
    "Spatula",
  ],
  salad: ["Chopping board", "Knife", "Serving bowl"],
  soup: [
    "Large pot",
    "Hob",
    "Colander",
    "Chopping board",
    "Knife",
    "Wooden spoon",
  ],
};
recipes.forEach((r) => (r.equipment = sampleEquipment[r.id]));
export const sampleMeals = [
  {
    id: "lemon-dinner",
    title: "Lemon orzo dinner",
    note: "A warm main, something fresh on the side.",
    components: [
      { id: "main-orzo", recipeId: "orzo", role: "Main", servings: 4 },
      { id: "side-salad", recipeId: "salad", role: "Side", servings: 4 },
    ],
  },
];
export const days = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday",
];
export const initial = {
  view: "library",
  selected: "orzo",
  query: "",
  filter: "all",
  servings: {},
  units: "metric",
  favorites: ["orzo", "tomato", "salad"],
  contributions: {},
  bought: {},
  manual: [],
  plan: [],
  session: null,
  notes: {},
  custom: [],
  meals: sampleMeals,
  selectedMeal: "lemon-dinner",
};
