// Generates shared/icons.js from the Lucide icon set installed in node_modules.
// Both apps draw their icons from that one generated module, so the browser
// app needs no bundler and the mobile app ships only the icons it uses.
//
//   node scripts/icons.mjs
import { writeFileSync, readFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = new URL("../", import.meta.url);
const lucide = JSON.parse(
  readFileSync(new URL("node_modules/lucide/package.json", root), "utf8"),
);
const names = [
  // Navigation
  "house",
  "book-open",
  "calendar-days",
  "shopping-basket",
  "cooking-pot",
  "settings",
  // Actions
  "plus",
  "minus",
  "search",
  "heart",
  "pencil",
  "trash",
  "x",
  "check",
  "chevron-left",
  "chevron-right",
  "chevron-down",
  "arrow-left",
  "arrow-right",
  "play",
  "pause",
  "share-2",
  "download",
  "upload",
  "undo-2",
  "ellipsis",
  "external-link",
  "log-in",
  "sparkles",
  "copy",
  "sliders-horizontal",
  "list-checks",
  // Kitchen
  "clock",
  "timer",
  "alarm-clock",
  "users",
  "user",
  "chef-hat",
  "utensils",
  "utensils-crossed",
  "refrigerator",
  "coins",
  "wallet",
  "receipt",
  "camera",
  "image",
  "clipboard-paste",
  "pen-line",
  "notebook-pen",
  "package",
  "snowflake",
  "flame",
  "leaf",
  "soup",
  "salad",
  "archive",
  "star",
  "bell",
  "bell-ring",
  "bell-off",
  "link",
  "file-text",
  "scale",
  "hourglass",
  "zap",
  "info",
  "circle-alert",
  "triangle-alert",
  "circle-check",
  "sun",
  "moon",
  "monitor",
  "wifi",
  "cloud-off",
  "database",
  "save",
  "repeat",
  "lock",
  "layers",
];

const attr = (value) => String(value).replace(/"/g, "&quot;");
const icons = {};
for (const name of names) {
  const file = new URL(`node_modules/lucide/dist/esm/icons/${name}.mjs`, root);
  const { default: nodes } = await import(pathToFileURL(fileURLToPath(file)));
  icons[name] = nodes
    .map(
      ([tag, attrs]) =>
        `<${tag} ${Object.entries(attrs)
          .map(([k, v]) => `${k}="${attr(v)}"`)
          .join(" ")}/>`,
    )
    .join("");
}

const out = `// Generated by scripts/icons.mjs from Lucide v${lucide.version} (ISC licence,
// https://lucide.dev). Do not edit by hand; add a name to the script and rerun it.
// Every icon is a 24-unit outline drawn with the current text colour.

export const icons = ${JSON.stringify(icons, null, 2)};

const escapeAttr = (value) =>
  String(value ?? "").replace(
    /[&<>"']/g,
    (c) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[
        c
      ],
  );

// An inline SVG for the named icon. Decorative by default; pass a label to
// make it meaningful to assistive technology. Unknown names fall back to the
// leaf so a typo never renders an empty box.
export function icon(name, { label = "", className = "" } = {}) {
  const body = icons[name] ?? icons.leaf;
  const a11y = label
    ? \`role="img" aria-label="\${escapeAttr(label)}"\`
    : 'aria-hidden="true"';
  return \`<svg class="icon\${className ? \` \${escapeAttr(className)}\` : ""}" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" \${a11y}>\${body}</svg>\`;
}
`;
writeFileSync(new URL("shared/icons.js", root), out);
console.log(`Wrote shared/icons.js with ${names.length} icons.`);
